---
name: Go CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test (Go ${{ matrix.go-version }})

    strategy:
      matrix:
        go-version: ['1.24']

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up just tool
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
      with:
        just-version: '1.40.0'

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Get dependencies
      run: >-
        just deps

    - name: Run tests
      run: >-
        just test
